# fly.toml file generated for delicate-firefly-1775 on 2021-05-03T16:03:54+01:00

app = "delicate-firefly-1775"

kill_signal = "SIGTERM"
kill_timeout = 5

[env]
  ENABLE_PAYMENTS = "true"

# Uncomment when we add the web endpoint
[[services]]
  internal_port = 4000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "30s" # Allow some time for startup
    interval = "15s"
    restart_limit = 6
    timeout = "2s"
