# fly.toml file generated for delicate-firefly-1775 on 2021-05-03T16:03:54+01:00

app = "delicate-firefly-1775"

kill_signal = "SIGTERM"
kill_timeout = 5

[env]
  ENABLE_PAYMENTS = "true"
  SENTRY_INGEST_URL = "https://b4ee84257c52464d9a9fb9a2409d3eea@o618213.ingest.sentry.io/5751153"

[deploy]
  release_command = "/app/bin/centraltipsbot eval Centraltipsbot.Release.migrate"

[[services]]
  internal_port = 4000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "30s" # Allow some time for startup
    interval = "15s"
    restart_limit = 6
    timeout = "2s"
